# Alacritty configuration file

[window]
  opacity = 0.92

# You can also set the background color to a specific color with an alpha channel.
# For example, to set the background to 50% transparent black, you would use the following:
#
# background_color = "rgba(0,0,0,0.5)"

[font]
  # Set the font size to 14 points.
  size = 13.5

[colors]

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
